services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=ubuntu
      - POSTGRES_PASSWORD=ubuntupass
      - POSTGRES_DB=sample-db
    ports:
      - "5445:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_volume:
