apiVersion: apps/v1
kind: Deployment
metadata:
  name: "debian"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "debian"
  template:
    metadata:
      labels:
        app: "debian"
    spec:
      containers:
      - name: "debian"
        image: "debian:latest"
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["-c", "while true; do sleep 30; done;"]
        # securityContext:
        #   readOnlyRootFilesystem: true
