{{- if .Values.service.gamma }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GRPCRoute
metadata:
  name: grpc-route
spec:
  parentRefs:
  - group: "default"
    kind: Service
    name: golang-grpc-server
    port: 8080
{{- end }}
