{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "golang-grpc.fullname" . }}
  labels:
    {{- include "golang-grpc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: grpc-port
  selector:
    {{- include "golang-grpc.selectorLabels" . | nindent 4 }}
{{- end }}
